### ISSUE TITLE
Seperate punishment from correction

### ISSUE THREAD

**Issue by bertvandepoel** [ULYSSIS-KUL/ipp#22]
Currently, when a team loses a lap as punishment for breaking the rules, it is entered the same way a potential correction would be. This is sementically of course not correct and would make inspecting replays/logs rather confusing. Perhaps a seperate option for punishments could be created that could also contain some kind of explentation field to further describe why punishment was given.

**Comment by RockinRoel** [comment]
Maybe we could add a reason field to the event?

**Comment by lesderid** [comment]
I agree, a reason field is probably better than making it a separate option internally.

Should the reason field's possible options be hard-coded (e.g. with an enum), or should the user be able to enter a reason string on-the-fly? I'd prefer the former for consistency and semantic machine-readability, but there might be arguments for the latter or a combination of both.

**Comment by RockinRoel** [comment]
You could have an enum with Correction/Penalty/Other and an optional explanation, so two extra fields.
