### ISSUE TITLE
Publisher pushes position 0.0 for team with 0 laps on FinalScore

### ISSUE THREAD

**Issue by bertvandepoel** [ULYSSIS-KUL/ipp#26]
I guess position 1.0 is prettier, even though 0.0 is more true.

**Comment by RockinRoel** [comment]
I think this is more up to the visualization, because 1.0 is indeed incorrect.

**Comment by bertvandepoel** [comment]
Well yeah, I could just overwrite it in JS, it's the same to me, it's just that on finalscore we put everyone else on 1.0

**Comment by RockinRoel** [comment]
Yeah, that's mostly because they eventually get to 1.0. I don't know if they should do that, or really just freeze at the last position.

**Comment by bertvandepoel** [comment]
Discussed this briefly with Vincent and @thomas-daniels . We consider it a better option to no longer publish position and speed on FinalScore, since both of these have no clear meaning or value at that point.

**Comment by RockinRoel** [comment]
Makes sense 🙂
